spring:
  datasource:
    url: jdbc:mysql://192.168.4.80:3306/kj_config?useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: bakheet001
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    init-sql: '"SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;"'
    hikari:
      minimum-idle: 10
      maximum-pool-size: 100

  redis:
    host: 192.168.4.80
    password: bakheet001
    port: 6379
    jedis:
      pool:
        max-wait: 1500ms
        max-active: 2048
        min-idle: 20
        max-idle: 200

suixingpay:
  autoload:
    cache:
      enable: true
  security: # 客户端安全校验用户名和密码
    username: admin
    password: 123456
